plugin: aws_ec2
regions:
  - "us-east-1" # aws de bu region'daki benim makinelerime bakiyor
filters: #filtrelerken tags bakiyor
  tag:Project: tera-kube-ans # main.tf de master makinesindeki tag'ler bunlar
  tag:environment: dev # main.tf de master makinesindeki tag'ler bunlar
keyed_groups:
  - key: tags['Project']
    prefix: 'all_instances'
  - key: tags['Role']
    prefix: 'role'
hostnames:
  - "ip-address"
compose:
  ansible_user: "'ubuntu'"
