kind: StorageClass # ihtiyacimiz oldugu kadar storage aliyoruz burda, dynamic olarak volume bagliyor
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com # csi = container storage interface
volumeBindingMode: WaitForFirstConsumer # WaitForFirstConsumer = bagla dendiginde bagliyor. otomatik yapmiyor. 
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1 
  iopsPerGB: "50"
  encrypted: "true"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - us-east-1a
